### ISSUE TITLE
getAdapterPosition() 的值可能会返回 -1

### ISSUE THREAD

**Issue by selfimprW** [Stay/PullRecycler#1]
onItemClick(v, getAdapterPosition());

**Comment by Stay** [comment]
umm.. there are some reason for no position
`if (viewHolder.hasAnyOfTheFlags( ViewHolder.FLAG_INVALID |
                ViewHolder.FLAG_REMOVED | ViewHolder.FLAG_ADAPTER_POSITION_UNKNOWN)
                || !viewHolder.isBound()) {
            return RecyclerView.NO_POSITION;
}`

try the latest commit, i fix bug with load more logic which may cause the problem.
